### PR TITLE
Create YAML

### PR DESCRIPTION
**Pull request by KYZITEMELOS93**

### CODE REVIEW

**Comment by mfs12** [comment]
@KYZITEMELOS93 interesting patch, does this also build the project?

**Comment by KYZITEMELOS93** [comment]
HAHA, IDK.
 I didn't get to finish trying to make it build itself and keep it private and keep it away from the actual master branch but I guess it got your attention.
 Not that it would make any sense but I was trying to see if I could make it an automated build because it's got me a bit frustrated not being able to set the PanelDue's connection properly.

**Comment by mfs12** [comment]
Hey, would be cool to have automated builds. Although i am not sure if this is possible with eclipse. Did you check there find out something about that? If so i would be very interested. Also there are a few build dependencies.

If you don't know already check https://github.com/Duet3D/PanelDueFirmware/blob/master/BuildInstructions.md for further details about building it.

**Comment by mfs12** [comment]
Hey @KYZITEMELOS93,

I close this PR due to inactivity for now and keep our PR list clean. If you disagree let's get in contact.

BTW headless build system based on cmake got integrated into master. Perhaps a good moment to reconsider this effort.

If you are interested in developing in github CI then let's get into contact and discuss some requirements.

**Pull request closed without merging**
