### PR TITLE
use cross compile variable

### PR DESCRIPTION
**Pull request by mfs12**
This simplifies setting up the cross compile environment. This way only one environment variable needs to be set and PATH stays unchanged.

Set in project properties -> C/C++ Build -> Build variable the variable CROSS_COMPILE to i.e. "/usr/bin/arm-none-eabi-".

Not sure if this will work as good on windows. Definitely needs a test  run.

### CODE REVIEW

**Comment by wilriker** [comment]
The build variable `ArmGccPath` is already used with all other RepRapFirmware related projects. I do not like this to be different just for this one project.

**Comment by mfs12** [comment]
I agree with you. It makes only sense if all project are going to be adapted in future. It was just an idea ;)

**Comment by dc42** [comment]
We definitely don't want to store this as a build variable in the .cproject file, because then different users would need different .cproject files. That's why we use a workspace variable instead.

**Comment by mfs12** [comment]
I wasn't aware of this difference, but makes totally sense to have it in the workspace configured and not in the project.

**Pull request closed without merging**
