### PR TITLE
Cmake improvements

### PR DESCRIPTION
**Pull request by mfs12**

### CODE REVIEW

**Comment by mfs12** [comment]
Hey @oliof, i updated support for windows and add hopefully complete support for white spaces in file paths. Can you run this once on you windows machine? If builds now properly in you environment.

It uses now WIN32 variable to check if it runs in windows. I am not 100% if this works properly.

**Comment by oliof** [comment]
CMake on Windows is unhappy with `-DDEVICE=5.0i`

```
PS C:\Users\Harald Wagener\PanelDueFirmware> cmake -B build -DDEVICE=5.0i .
-- Building for: Visual Studio 16 2019
ARM-NONE-EABI GCC found: C:/Program Files (x86)/GNU Tools ARM Embedded/8 2018-q4-major/bin/arm-none-eabi-gcc.exe
ARM-NONE-EABI GCC Path: C:/Program Files (x86)/GNU Tools ARM Embedded/8 2018-q4-major/bin
ARM-NONE-EABI Cross Compile: arm-none-eabi-
Toolchain C_FLAGS: --param max-inline-insns-single=500 -mlong-calls -ffunction-sections -fdata-sections -fno-exceptions -fsingle-precision-constant -Wall -Wextra -Wundef -Wdouble-promotion -Wno-expansion-to-defined -std=gnu99
Toolchain CXX_FLAGS: --param max-inline-insns-single=500 -mlong-calls -ffunction-sections -fdata-sections -fno-exceptions -fsingle-precision-constant -Wall -Wextra -Wundef -Wdouble-promotion -Wno-expansion-to-defined -std=gnu++17 -fno-threadsafe-statics -fno-rtti
Toolchain ASM_FLAGS: --param max-inline-insns-single=500 -mlong-calls -ffunction-sections -fdata-sections -fno-exceptions -fsingle-precision-constant -Wall -Wextra -Wundef -Wdouble-promotion -Wno-expansion-to-defined
Toolchain LD_FLAGS:
ARM-NONE-EABI GCC found: C:/Program Files (x86)/GNU Tools ARM Embedded/8 2018-q4-major/bin/arm-none-eabi-gcc.exe
ARM-NONE-EABI GCC Path: C:/Program Files (x86)/GNU Tools ARM Embedded/8 2018-q4-major/bin
ARM-NONE-EABI Cross Compile: arm-none-eabi-
Toolchain C_FLAGS: --param max-inline-insns-single=500 -mlong-calls -ffunction-sections -fdata-sections -fno-exceptions -fsingle-precision-constant -Wall -Wextra -Wundef -Wdouble-promotion -Wno-expansion-to-defined -std=gnu99
Toolchain CXX_FLAGS: --param max-inline-insns-single=500 -mlong-calls -ffunction-sections -fdata-sections -fno-exceptions -fsingle-precision-constant -Wall -Wextra -Wundef -Wdouble-promotion -Wno-expansion-to-defined -std=gnu++17 -fno-threadsafe-statics -fno-rtti
Toolchain ASM_FLAGS: --param max-inline-insns-single=500 -mlong-calls -ffunction-sections -fdata-sections -fno-exceptions -fsingle-precision-constant -Wall -Wextra -Wundef -Wdouble-promotion -Wno-expansion-to-defined
Toolchain LD_FLAGS:
-- The C compiler identification is MSVC 19.28.29337.0
-- The CXX compiler identification is MSVC 19.28.29337.0
CMake Error at CMakeLists.txt:123 (message):
  Please configure a device cmake
  -DDEVICE=v2-4.3|v2-5.0|v2-7.0|v2-7.0c|v3-4.3|v3-5.0|v3-7.0|v3-7.0c|5.0i|7.0i


-- Configuring incomplete, errors occurred!
See also "C:/Users/Harald Wagener/PanelDueFirmware/build/CMakeFiles/CMakeOutput.log".
PS C:\Users\Harald Wagener\PanelDueFirmware>
```

CMake on WSL still doesn't like spaces in directory names (because the WIN32 variable isn't set, since it's a native Linux environment).

**Comment by mfs12** [comment]
Hey @oliof, i think you didn't checkout the updated branch. Please also have look into  the updated Readme.md. There are new instructions to configure the cross compiler with another variable. It should be easier and more reliable than before.

**Comment by oliof** [comment]
I did pull the master branch before running the tests. Do I need to use another branch for testing?

**Comment by mfs12** [comment]
Hey @oliof , yes, you need to check-out this branch

https://github.com/mfs12/PanelDueFirmware/tree/cmake-improvements

**Comment by oliof** [comment]
That branch doesn't exit upstream yet, only your uncommited PR. I did check it out with `git fetch origin pull/179/head:cmake-improvements` and still run into issues:

```
PS C:\Users\Harald Wagener\PanelDueFirmware> git branch
* cmake-improvements
  master
PS C:\Users\Harald Wagener\PanelDueFirmware> git rev-parse HEAD
d45572362763a7d54fce4100af21ea9b0fb45cd6
PS C:\Users\Harald Wagener\PanelDueFirmware> cmake -B build -DDEVICE=5.0i -DCROSS_COMPILE="C:/Program Files (x86)/GNU Tools ARM Embedded/8 2018-q4-major/bin/arm-none-eabi-" .
-- Building for: Visual Studio 16 2019
CROSS_COMPILE: C:/Program Files (x86)/GNU Tools ARM Embedded/8 2018-q4-major/bin/arm-none-eabi-
Toolchain definition:
  asm: C:/Program Files (x86)/GNU Tools ARM Embedded/8 2018-q4-major/bin/arm-none-eabi-gcc.exe
  c: C:/Program Files (x86)/GNU Tools ARM Embedded/8 2018-q4-major/bin/arm-none-eabi-gcc.exe
  cxx: C:/Program Files (x86)/GNU Tools ARM Embedded/8 2018-q4-major/bin/arm-none-eabi-g++.exe
  ar: C:/Program Files (x86)/GNU Tools ARM Embedded/8 2018-q4-major/bin/arm-none-eabi-ar.exe
  objcopy: C:/Program Files (x86)/GNU Tools ARM Embedded/8 2018-q4-major/bin/arm-none-eabi-objcopy.exe
  objdump: C:/Program Files (x86)/GNU Tools ARM Embedded/8 2018-q4-major/bin/arm-none-eabi-objdump.exe
  C_FLAGS: --param max-inline-insns-single=500 -mlong-calls -ffunction-sections -fdata-sections -fno-exceptions -fsingle-precision-constant -Wall -Wextra -Wundef -Wdouble-promotion -Wno-expansion-to-defined -std=gnu99
  CXX_FLAGS: --param max-inline-insns-single=500 -mlong-calls -ffunction-sections -fdata-sections -fno-exceptions -fsingle-precision-constant -Wall -Wextra -Wundef -Wdouble-promotion -Wno-expansion-to-defined -std=gnu++17 -fno-threadsafe-statics -fno-rtti
  ASM_FLAGS: --param max-inline-insns-single=500 -mlong-calls -ffunction-sections -fdata-sections -fno-exceptions -fsingle-precision-constant -Wall -Wextra -Wundef -Wdouble-promotion -Wno-expansion-to-defined
  LD_FLAGS:
CROSS_COMPILE: C:/Program Files (x86)/GNU Tools ARM Embedded/8 2018-q4-major/bin/arm-none-eabi-
Toolchain definition:
  asm: C:/Program Files (x86)/GNU Tools ARM Embedded/8 2018-q4-major/bin/arm-none-eabi-gcc.exe
  c: C:/Program Files (x86)/GNU Tools ARM Embedded/8 2018-q4-major/bin/arm-none-eabi-gcc.exe
  cxx: C:/Program Files (x86)/GNU Tools ARM Embedded/8 2018-q4-major/bin/arm-none-eabi-g++.exe
  ar: C:/Program Files (x86)/GNU Tools ARM Embedded/8 2018-q4-major/bin/arm-none-eabi-ar.exe
  objcopy: C:/Program Files (x86)/GNU Tools ARM Embedded/8 2018-q4-major/bin/arm-none-eabi-objcopy.exe
  objdump: C:/Program Files (x86)/GNU Tools ARM Embedded/8 2018-q4-major/bin/arm-none-eabi-objdump.exe
  C_FLAGS: --param max-inline-insns-single=500 -mlong-calls -ffunction-sections -fdata-sections -fno-exceptions -fsingle-precision-constant -Wall -Wextra -Wundef -Wdouble-promotion -Wno-expansion-to-defined -std=gnu99
  CXX_FLAGS: --param max-inline-insns-single=500 -mlong-calls -ffunction-sections -fdata-sections -fno-exceptions -fsingle-precision-constant -Wall -Wextra -Wundef -Wdouble-promotion -Wno-expansion-to-defined -std=gnu++17 -fno-threadsafe-statics -fno-rtti
  ASM_FLAGS: --param max-inline-insns-single=500 -mlong-calls -ffunction-sections -fdata-sections -fno-exceptions -fsingle-precision-constant -Wall -Wextra -Wundef -Wdouble-promotion -Wno-expansion-to-defined
  LD_FLAGS:
-- The C compiler identification is MSVC 19.28.29337.0
-- The CXX compiler identification is MSVC 19.28.29337.0
CMake Error at CMakeLists.txt:123 (message):
  Please configure a device cmake
  -DDEVICE=v2-4.3|v2-5.0|v2-7.0|v2-7.0c|v3-4.3|v3-5.0|v3-7.0|v3-7.0c|5.0i|7.0i


-- Configuring incomplete, errors occurred!
See also "C:/Users/Harald Wagener/PanelDueFirmware/build/CMakeFiles/CMakeOutput.log".
PS C:\Users\Harald Wagener\PanelDueFirmware>
```

Please note that for some reason CMake picks up MSVC as C and C++ compilers despite the cross compile environment variable being set. if I run

` cmake -G "Unix Makefiles" -B build -DDEVICE=5.0i -DCROSS_COMPILE="C:/Program Files (x86)/GNU Tools ARM Embedded/8 2018-q4-major/bin/arm-none-eabi-" .`, the GCC binaries are picked up, but the -DDEVICE directive still is ignored.

**Comment by mfs12** [comment]
ok. this looks definitely better. although in don't understand why cmake doesn't accept the device variable. Does it help putting it into quotations?

**Comment by mfs12** [comment]
add a minor tweak. so updating your branch is necessary.

**Comment by oliof** [comment]
Yes, I habitually do `rm build\*`  (-: 

I haven't pulled your latest change yet. This command stanza finishes without error:

cmake -G "Unix Makefiles" -B build -DDEVICE="5.0i" -DCROSS_COMPILE="C:/Program Files (x86)/GNU Tools ARM Embedded/8 2018-q4-major/bin/arm-none-eabi-" .

but now I get the issue with the space in the path again (this time in build.make since I generated Unix Makefiles). I will grab your latest change and try again.

**Comment by oliof** [comment]
With the latest revision of this PR, the linker path to `flash.ld` is properly escaped and I can build without manual intervention running the following commands:

```
$ cmake -G "Unix Makefiles" -B build -DDEVICE="5.0i" -DCROSS_COMPILE="C:/Program\ Files\ (x86)/GNU\ Tools\ ARM\ Embedded/8\ 2018-q4-major/bin/arm-none-eabi-" .
$ make -C build all
```

**Comment by mfs12** [comment]
@oliof thanks a lot for testing and reporting back! I already updated the readme file as well.

**Pull request merged**
