### PR TITLE
Added Ukrainian translation

### PR DESCRIPTION
**Pull request by vitaliy172**
Sorry about auto-format

### CODE REVIEW

**Comment by wilriker** [comment]
@vitaliy172 Thanks for your contribution! Have you checked that everything is displayed correctly with the included font? This only provides a limited set of characters and TBH (since I did not compile the font) I don't know if it contains the required Cyrillic characters.

**Comment by dc42** [comment]
To create fonts we use GLCD Font Creator. This is a Windows program that has to be run in XP compatibility mode (unless they have updated it). The input font must be FOSS so we use Liberation Sans. You need to tell it to remove all blank rows and columns from the top, bottom and sides. You have to find the required input font size to generate the correct output width and height by trial and error. Some manual editing of the font is usually needed to clean it up,.

**Comment by vitaliy172** [comment]
What size do they need to be?

**Comment by wilriker** [comment]
Please check the `src/Fonts` folder. The fonts currently in use are 19x21 and 28x32. These files also contain some settings for GLCD.

**Comment by vitaliy172** [comment]
I can't understand anything. Can you please do that?

**Comment by wilriker** [comment]
I'm looking into it.

**Comment by wilriker** [comment]
@vitaliy172 Can you please tell me which version of PanelDue you are using so I can provide you with a test-build? It seems to look OK but since I do not read Cyrillic I cannot tell for sure.

**Comment by vitaliy172** [comment]
Unfortunately, I can't afford it, I just translate stuff. Maybe you can send photos?

**Comment by wilriker** [comment]
IMG_20210112_100646
IMG_20210112_100651
IMG_20210112_100656
IMG_20210112_100719

**Comment by vitaliy172** [comment]
Everything looks good! But on last photo, some labels got cut. Maybe I should try to make them smaller?

**Comment by wilriker** [comment]
@vitaliy172 I have merged your contribution manually. Thanks for your effort!

The code is disabled though for now until there is a request for this translation (and/or possibly other Cyrillic languages) since it takes up a lot of flash memory.

**Pull request closed without merging**
